name: PR Builder

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  review:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
    - name: Verify Version
      run: node ./.github/scripts/verify-version.js

  review-merged:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Merge Master
      run: git merge origin/master
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
